package io.justtrack.ads

import io.justtrack.events.Money

/**
 * Represents an ad impression to be sent to the justtrack backend. This class is used to collect
 * data related to ad impressions, which can be utilized to calculate the ad revenue generated by
 * your app.
 */
data class AdImpression(
    /**
     * The unit for this ad impression.
     */
    val unit: String,
    /**
     * The sdkName for this ad impression.
     */
    val sdkName: String,
    /**
     * The network for this ad impression.
     */
    var network: String? = null,
    /**
     * The placement of the ad. May be null.
     */
    var placement: String? = null,
    /**
     * The test group of the user if we are A/B testing. May be null.
     */
    var testGroup: String? = null,
    /**
     * The name of the segment of the ad. May be null.
     */
    var segmentName: String? = null,
    /**
     * The name of the instance of the ad. May be null.
     */
    var instanceName: String? = null,
    /**
     * The bundle ID of the advertised app. May be null.
     */
    var bundleId: String? = null,
    /**
     * The amount of revenue this ad generated. May be zero but must not be negative.
     */
    var revenue: Money? = null,

    /**
     * The state of the ad impression. May be null.
     */
    val state: AdImpressionState? = null,
) {

    constructor(
        unit: AdUnit,
        sdkName: String,
        network: String? = null,
        placement: String? = null,
        testGroup: String? = null,
        segmentName: String? = null,
        instanceName: String? = null,
        bundleId: String? = null,
        revenue: Money? = null,
        state: AdImpressionState? = null,
    ) : this(
        unit.encodedName,
        sdkName,
        network,
        placement,
        testGroup,
        segmentName,
        instanceName,
        bundleId,
        revenue,
        state,
    )
}

/**
 * The unit for an ad impression state.
 */
enum class AdImpressionState(
    /** The encoded name of this state. */
    val encodedName: String,
) {
    /**
     * The impression was skipped.
     */
    SKIPPED("skipped"),

    /**
     * The impression was completed.
     */
    COMPLETED("completed"),
}
