ext {
    getVersionMajor = (def project) -> {
        //getting the right android version code
        def versionPropsFile = file("$project.rootDir/sdk/deployment/version.properties")

        if (versionPropsFile.canRead()) {
            Properties versionProps = new Properties()

            versionProps.load(new FileInputStream(versionPropsFile))

            versionProps['VERSION_MAJOR'].toInteger()
        } else {
            throw new RuntimeException("No $project.rootDir/sdk/deployment/version.properties found")
        }
    }

    getVersionMinor = (def project) -> {
        //getting the right android version name
        def versionPropsFile = file("$project.rootDir/sdk/deployment/version.properties")

        if (versionPropsFile.canRead()) {
            Properties versionProps = new Properties()

            versionProps.load(new FileInputStream(versionPropsFile))

            versionProps['VERSION_MINOR'].toInteger()
        } else {
            throw new RuntimeException("No $project.rootDir/sdk/deployment/version.properties found")
        }
    }

    getVersionPatch = (def project) -> {
        //getting the right android version name
        def versionPropsFile = file("$project.rootDir/sdk/deployment/version.properties")

        if (versionPropsFile.canRead()) {
            Properties versionProps = new Properties()

            versionProps.load(new FileInputStream(versionPropsFile))

            versionProps['VERSION_PATCH'].toInteger()
        } else {
            throw new RuntimeException("No $project.rootDir/sdk/deployment/version.properties found")
        }
    }

    getVersionType = (def project) -> {
        //getting the right android version name
        def versionPropsFile = file("$project.rootDir/sdk/deployment/version.properties")

        if (versionPropsFile.canRead()) {
            Properties versionProps = new Properties()

            versionProps.load(new FileInputStream(versionPropsFile))

            versionProps['VERSION_TYPE'].toString()
        } else {
            throw new RuntimeException("No $project.rootDir/sdk/deployment/version.properties found")
        }
    }
}
